LotteryMVC/LotteryMVC/Models/HistoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LotteryMVC.Models
{
    public class HistoryViewModel
    {

        public List<Note> Notes { get; set; }
        public PageViewModel PageViewModel { get; set; }
    }
}

LotteryMVC/LotteryMVC/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LotteryMVC.Data;
using LotteryMVC.Models;
using LotteryMVC.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LotteryMVC.Controllers
{
    [Authorize]
    public class HistoryController : Controller
    {
       
        private readonly UserManager<User> _userManager;
        private readonly HistoryService _historyService;
        public HistoryController(UserManager<User> userManager,HistoryService historyService)
        {
            _userManager = userManager;
            _historyService = historyService;
        }

        public IActionResult Index(int page = 0)
        {
            int NoteCount = 10;

            
            User user = _userManager.GetUserAsync(User).Result;
            string id = user.Id;

            IQueryable<Note> notes = _historyService.GetHistoryNotes(id);
            var count = notes.Count();
            if (page < 1) page = (count / NoteCount)+1;
            var items = notes.Skip((page - 1) * NoteCount).Take(NoteCount).ToList();
            

            PageViewModel pageViewModel = new PageViewModel(count, page, NoteCount);
            HistoryViewModel viewModel = new HistoryViewModel
            {
                PageViewModel = pageViewModel,
                Notes = items
            };
            return View(viewModel);
        }

        [Authorize(Roles = "admin")]
        public IActionResult UserHistory(string userid,int page = 1)
        {
            
            int NoteCount = 10;

            string id = userid;

            IQueryable<Note> notes = _historyService.GetHistoryNotes(id);
            var count = notes.Count();
            if (page < 1) page = (count / NoteCount) + 1;
            var items = notes.Skip((page - 1) * NoteCount).Take(NoteCount).ToList();


            PageViewModel pageViewModel = new PageViewModel(count, page, NoteCount);
            HistoryViewModel viewModel = new HistoryViewModel
            {
                PageViewModel = pageViewModel,
                Notes = items
            };

            ViewData["userid"] = userid;

            return View(viewModel);
        }

        [Authorize(Roles ="admin")]
        public IActionResult AddNote(string userid)
        {
            AddNoteModel m = new AddNoteModel();
            m.UserID = userid;
            return View(m);
        }

        [Authorize(Roles ="admin")]
        [HttpPost]
        public IActionResult AddNote(AddNoteModel notify)
        {
            _historyService.AddDefaultNote(notify.Text, notify.UserID);
            return RedirectToAction("Index", "Users");
        }
    }
}

LotteryMVC/LotteryMVC/Views/History/AddNote.cshtml
@model LotteryMVC.Models.AddNoteModel
@{
    ViewBag.Title = "New notify";
}

<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form asp-action="AddNote" asp-controller="History">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <input type="hidden" asp-for="UserID" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Text" class="control-label">text</label>
                        <input type="text" asp-for="Text" class="form-control" />
                    </div>
                    
                    <div class="form-group">
                        <input type="submit" value="Send" class="btn btn-default" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header> 

LotteryMVC/LotteryMVC/Views/History/Index.cshtml
@using System.Text.Json
@model HistoryViewModel
@{
    ViewData["Title"] = "Index";
}

    <header class="masthead text-center text-white">
        <div class="masthead-content">
            <div class="container">

                @foreach (var note in Model.Notes)
                {

                    switch (note.Type)
                    {
                        case 0:
                            {
                                NotifyGameResultModel v = JsonSerializer.Deserialize<NotifyGameResultModel>(note.Json);
                                @if (v.Win)
                                {
                                    <div class="alert alert-success">
                                        @note.Date @v.Text @v.Money  Game#@v.GameIdentifier
                                    </div>
                                }
                                else
                                {
                                    <div class="alert alert-danger">
                                        @note.Date @v.Text  Game#@v.GameIdentifier
                                    </div>
                                }
                            }
                            break;
                        default:
                            {
                                NotifyModel v = JsonSerializer.Deserialize<NotifyModel>(note.Json);
                                <div class="alert alert-info">
                                    @note.Date   @v.Text
                                </div>
                                break;
                            }

                    }

                }
                @if (Model.PageViewModel.HasPreviousPage)
                {
                    <a asp-action="Index"
                       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
                       class="btn btn-primary btn">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Назад
                    </a>
                }
                @if (Model.PageViewModel.HasNextPage)
                {
                    <a asp-action="Index"
                       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
                       class="btn btn-primary">
                        Вперед
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </a>
                }
            </div>
        </div>
        <div class="bg-circle-1 bg-circle"></div>
        <div class="bg-circle-2 bg-circle"></div>
        <div class="bg-circle-3 bg-circle"></div>
        <div class="bg-circle-4 bg-circle"></div>
    </header>

LotteryMVC/LotteryMVC/Views/History/UserHistory.cshtml
@using System.Text.Json
@model HistoryViewModel
@{
    ViewData["Title"] = "Index";
}

    <header class="masthead text-center text-white">
        <div class="masthead-content">
            <div class="container">
                <h1>History of User with id = @ViewData["userid"]</h1>
                @foreach (var note in Model.Notes)
                {
                    @note.Date
                    switch (note.Type)
                    {
                        case 0:
                            {
                                NotifyGameResultModel v = JsonSerializer.Deserialize<NotifyGameResultModel>(note.Json);
                                @if (v.Win)
                                {
                                    <div class="alert alert-success">
                                        @v.Text @v.Money  Game#@v.GameIdentifier
                                    </div>
                                }
                                else
                                {
                                    <div class="alert alert-danger">
                                        @v.Text @v.Money  Game#@v.GameIdentifier
                                    </div>
                                }
                            }
                            break;
                        default:
                            {
                                NotifyModel v = JsonSerializer.Deserialize<NotifyModel>(note.Json);
                                <div class="alert alert-info">
                                    @v.Text
                                </div>
                                break;
                            }

                    }

                }
                @if (Model.PageViewModel.HasPreviousPage)
                {
                    <a asp-action="UserHistory"
                       asp-route-userid="@ViewData["userid"]"
                       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
                       class="btn btn-default btn">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Назад
                    </a>
                }
                @if (Model.PageViewModel.HasNextPage)
                {
                    <a asp-action="UserHistory"
                       asp-route-userid="@ViewData["userid"]"
                       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
                       class="btn btn-default btn">
                        Вперед
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </a>
                }
            </div>
        </div>
        <div class="bg-circle-1 bg-circle"></div>
        <div class="bg-circle-2 bg-circle"></div>
        <div class="bg-circle-3 bg-circle"></div>
        <div class="bg-circle-4 bg-circle"></div>
    </header>